services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "3080:8080"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
